os: osx
osx_image: xcode10.2
branches:
  only:
    - master
language: swift
xcode_workspace: LolayIllud.xcworkspace
xcode_scheme: LolayIllud
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone Xs
xcode_sdk: iphonesimulator12.2

